package com.santandar.market.dynamodb.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.Date;

@Setter
@Getter
@Builder
@ToString
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Instrument")
public class Instrument {
    private String id;
    private String instrumentName;
    private double bid;
    private double ask;
    private Date timestamp;
    private double updatedBid;
    private double updatedAsk;
    private Date updateDt;

    @DynamoDBHashKey
    //  @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getInstrumentName() {
        return instrumentName;
    }

    @DynamoDBAttribute
    public double getBid() {
        return bid;
    }

    @DynamoDBAttribute
    public double getAsk() {
        return ask;
    }

    @DynamoDBAttribute
    public Date getTimestamp() {
        return timestamp;
    }

    @DynamoDBAttribute
    public Date getUpdateDt() {
        return updateDt;
    }

    @DynamoDBAttribute
    public double getUpdatedBid() {
        return updatedBid;
    }

    @DynamoDBAttribute
    public double getUpdatedAsk() {
        return updatedAsk;
    }

}